version: "3.7"

networks:
  frontend:
  backend:

volumes:
  pgdata:
  opdata:

services:
  db:
    image: postgres:13
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-openproject}"
      POSTGRES_DB: openproject
      POSTGRES_USER: postgres

  cache:
    image: memcached
    restart: unless-stopped
    networks:
      - backend

  seeder:
    image: openproject/openproject:15-slim
    restart: on-failure
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-false}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-project.christopherfullon.com}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD:-openproject}@db/openproject?pool=100"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      USE_PUMA: "true"
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
    depends_on:
      - db
      - cache
    networks:
      - backend
    command: "./docker/prod/seeder"

  web:
    image: openproject/openproject:15-slim
    restart: unless-stopped
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-false}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-project.christopherfullon.com}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD:-openproject}@db/openproject?pool=100"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      USE_PUMA: "true"
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
    depends_on:
      - db
      - cache
      - seeder
    networks:
      - frontend
      - backend
    ports:
      - "8356:8080"
    command: "./docker/prod/web"

  worker:
    image: openproject/openproject:15-slim
    restart: unless-stopped
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-false}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-project.christopherfullon.com}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD:-openproject}@db/openproject?pool=100"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      USE_PUMA: "true"
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
    depends_on:
      - db
      - cache
      - seeder
    networks:
      - backend
    command: "./docker/prod/worker"

  cron:
    image: openproject/openproject:15-slim
    restart: unless-stopped
    environment:
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-false}"
      OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-project.christopherfullon.com}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD:-openproject}@db/openproject?pool=100"
      OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
      USE_PUMA: "true"
    volumes:
      - "${OPDATA:-opdata}:/var/openproject/assets"
    depends_on:
      - db
      - cache
      - seeder
    networks:
      - backend
    command: "./docker/prod/cron"
