FROM python:3.11-slim

WORKDIR /app

RUN apt-get update -y
RUN apt-get install -y --no-install-recommends git ffmpeg libsndfile1 build-essential

RUN git clone https://github.com/ace-step/ACE-Step-1.5.git /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 7860
EXPOSE 8001

CMD ["python", "-m", "acestep.api_server", "--host", "0.0.0.0", "--port", "8001"]
