FROM python:3.11-slim

RUN apt-get update -y

RUN apt-get install -y --no-install-recommends inkscape

WORKDIR /app

RUN pip install flask --no-cache-dir

COPY renderer-server.py /app/server.py

RUN mkdir -p /app/inputs /app/outputs

EXPOSE 8766

CMD ["python", "/app/server.py"]
