version: "3.7"

networks:
  frontend:
  backend:

volumes:
  pgdata:
  opdata:

x-op-restart-policy: &restart_policy
  restart: unless-stopped

x-op-image: &image
  image: openproject/openproject:15-slim

x-op-app: &app
  <<: *image
  <<: *restart_policy
  environment:
    OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-false}"
    OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-project.christopherfullon.com}"
    SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    DATABASE_URL: "postgresql://postgres:${DB_PASSWORD:-openproject}@db/openproject?pool=100"
    OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
    USE_PUMA: "true"
  volumes:
    - "${OPDATA:-opdata}:/var/openproject/assets"
  depends_on:
    - db
    - cache

services:
  db:
    image: postgres:13
    <<: *restart_policy
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-openproject}"
      POSTGRES_DB: openproject
      POSTGRES_USER: postgres

  cache:
    image: memcached
    <<: *restart_policy
    networks:
      - backend

  web:
    <<: *app
    networks:
      - frontend
      - backend
    ports:
      - "${PORT:-8356}:8080"
    command: "./docker/prod/web"

  worker:
    <<: *app
    networks:
      - backend
    command: "./docker/prod/worker"

  cron:
    <<: *app
    networks:
      - backend
    command: "./docker/prod/cron"

  seeder:
    <<: *app
    networks:
      - backend
    command: "./docker/prod/seeder"
    restart: on-failure
