version: "3.7"

networks:
  social_network:
    external: true
    name: social-stack_social_network

volumes:
  registry_data:

services:
  target-registry:
    build:
      context: .
      dockerfile: Dockerfile.registry
    restart: unless-stopped
    networks:
      - social_network
    ports:
      - "8769:8769"
    volumes:
      - registry_data:/app/targets
    environment:
      PYTHONUNBUFFERED: "1"
